name: Renovate

on:
  # Esegui al push sul branch main
  push:

  # Consenti esecuzione manuale
  workflow_dispatch: {}

concurrency: renovate

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      id-token: write
      pull-requests: write
      issues: read
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Validate Renovate configuration
        run: jq type .github/renovate.json

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.22
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM_COMMIT: "true"
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.ACCESS_TOKEN }}  # o GITHUBname: Renovate

on:
  # Run on push to main branch
  push:
    branches:
      - main
  # Allow manual execution
  workflow_dispatch: {}

concurrency: renovate

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      id-token: write  # Required for AWS OIDC authentication
      pull-requests: write
      issues: read
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::281670075220:role/Renovate-Dennis_DynamicToken
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true

      - name: Set ECR credential in environment
        run: |
          # Get temporary ECR credentials and set them as environment variables
          TOKEN=$(aws ecr get-authorization-token --region eu-central-1 --output text --query 'authorizationData[].authorizationToken')
          echo "ECR_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Validate Renovate configuration
        run: jq type .github/renovate.json

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.22
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM_COMMIT: "true"
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
          # Pass the ECR credentials to Renovate
          RENOVATE_HOST_RULES: '[{"matchHost":"281670075220.dkr.ecr.eu-central-1.amazonaws.com","authType":"Basic","username":"AWS","password":"${{ env.ECR_TOKEN }}"}]'
        with:
          configurationFile: renovate.json
          token: ${{ secrets.ACCESS_TOKEN }}_TOKEN se usi solo quello
