name: Renovate

on:
  # Esegui al push sul branch main
  push:

  # Consenti esecuzione manuale
  workflow_dispatch: {}

concurrency: renovate

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      id-token: write
      pull-requests: write
      issues: read
      statuses: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Validate Renovate configuration
        run: jq type .github/renovate.json

      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.22
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM_COMMIT: "true"
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
        with:
          configurationFile: renovate.json
          token: ${{ secrets.ACCESS_TOKEN }}  # o GITHUB_TOKEN se usi solo quello
